version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: wagtail-app:latest
    container_name: studevph_web
    expose:
      - "8000"
    environment:
      PYTHONUNBUFFERED: "1"
      PORT: "8000"
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      LETSENCRYPT_HOST: ${LETSENCRYPT_HOST}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
    volumes:
      - wagtail_data:/app
      - static_volume:/app/static
      - media_volume:/app/media
    restart: unless-stopped
  nginx_proxy:
    image: jwilder/nginx-proxy:alpine
    container_name: nginx_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - nginx_certs:/etc/nginx/certs:rw
      - nginx_vhost:/etc/nginx/vhost.d:rw
      - nginx_html:/usr/share/nginx/html:rw
    restart: unless-stopped
  nginx:
    image: nginx:1.25-alpine
    container_name: wagtail_nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      web:
        condition: service_started
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/ssl:ro
      - static_volume:/static:ro
      - media_volume:/media:ro
    restart: unless-stopped

volumes:
  wagtail_data:
    driver: local
  static_volume:
    driver: local
  media_volume:
    driver: local
  nginx_certs:
    driver: local
  nginx_vhost:
    driver: local
  nginx_html:
    driver: local