version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: wagtail-app:latest
    container_name: studevph_web
    expose:
      - "8000"
    environment:
      PYTHONUNBUFFERED: "1"
      PORT: "8000"
    volumes:
      - wagtail_data:/app
      - static_volume:/app/static
      - media_volume:/app/media
    restart: unless-stopped

  nginx:
    image: nginx:1.25-alpine
    container_name: wagtail_nginx
    ports:
      - "80:80"
    depends_on:
      - web
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - static_volume:/static:ro
      - media_volume:/media:ro
    restart: unless-stopped

volumes:
  wagtail_data:
    driver: local
  static_volume:
    driver: local
  media_volume:
    driver: local